### ISSUE TITLE
post support

### ISSUE THREAD

**Issue by mimez** [paullockaby/enphase-proxy#48]
Hey,

first of all i want to say thank you. awesome job done here. 

I am using your proxy to fetch data from envoy. now i encountered a problem with /ivp/livedata/status. This endpoint just returns current values if the livedata is enabeld. in any other case it returns old data. due to a forum post (https://support.enphase.com/s/question/0D53m00008sfiRcCAI/live-status-via-envoy-or-the-app-offline-feature-freezes) it should be able to enable the live data by sending a post request like this:

`curl -k -H "Content-Type:application/json" -d "{\"enable\":1}" http://IP/ivp/livedata/stream`

Unfortunately i get a method not allowed error:

`
<!doctype html>
<html lang=en>
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested `URL.</p>
`

therefore i want to ask: do you want to implement multiple methods (GET/POST)? it would be great

cheers, michael

**Comment by plockaby** [comment]
Done. Thanks for the recommendation!
